[package]
name = "readany-render-fuzz"
version = "0.0.0"
publish = false
edition = "2024"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
readany-render = { version = "0.1.0", path = "../crates/readany-render", features = ["fuzzing"] }

[[bin]]
name = "render"
path = "fuzz_targets/render.rs"
test = false
doc = false
bench = false

[[bin]]
name = "font"
path = "fuzz_targets/font.rs"
test = false
doc = false
bench = false

[[bin]]
name = "csv"
path = "fuzz_targets/csv.rs"
test = false
doc = false
bench = false

[[bin]]
name = "xlsx"
path = "fuzz_targets/xlsx.rs"
test = false
doc = false
bench = false

[[bin]]
name = "ods"
path = "fuzz_targets/ods.rs"
test = false
doc = false
bench = false

[[bin]]
name = "docx"
path = "fuzz_targets/docx.rs"
test = false
doc = false
bench = false

[[bin]]
name = "odt"
path = "fuzz_targets/odt.rs"
test = false
doc = false
bench = false

[[bin]]
name = "rtf"
path = "fuzz_targets/rtf.rs"
test = false
doc = false
bench = false

[[bin]]
name = "pptx"
path = "fuzz_targets/pptx.rs"
test = false
doc = false
bench = false

[[bin]]
name = "odp"
path = "fuzz_targets/odp.rs"
test = false
doc = false
bench = false

[[bin]]
name = "image"
path = "fuzz_targets/image.rs"
test = false
doc = false
bench = false

[[bin]]
name = "zip"
path = "fuzz_targets/zip.rs"
test = false
doc = false
bench = false

[[bin]]
name = "xml"
path = "fuzz_targets/xml.rs"
test = false
doc = false
bench = false
